### ISSUE TITLE
android freezes or restart

### ISSUE THREAD

**Issue by promeneur** [wolpi/prim-ftpd#12] opened 2014-09-09 13:38 UTC
Samsung s2 plus
android 4.2.2

i start primitive ftpd
then
android freezes
or
restart !

i must try several times before to use it without freeze or restart

**Comment by wolpi** [comment] 2015-03-29 21:39
figured out that this is caused by the bonjour announcements, at least on some devices. Updated the description of the preference and switched it off by default. (will be included in next version)

**Closed by wolpi** 2015-03-29 21:39 UTC
