### ISSUE TITLE
Setting the server start directory doesn't work; storage directory inaccessible

### ISSUE THREAD

**Issue by l0b0** [wolpi/prim-ftpd#67] opened 2016-06-24 18:52 UTC
How to reproduce in version 4.5:

1. Enable password-authenticated SFTP login.
1. Set the server start directory to for example `/storage`.
1. Verify that the "Directory is not valid" message does *not* appear.
1. Restart the server.
1. `sshfs phone: /media/phone`
1. `cd /media/phone`

At this point I'm clearly seeing the root directory of the phone, and the storage directory is not accessible:

```
$ ls -l 
ls: cannot access 'sdcard': Input/output error
ls: cannot access 'storage': Input/output error
ls: cannot access 'vendor': Input/output error
ls: cannot access 'd': Input/output error
ls: cannot access 'etc': Input/output error
ls: cannot access 'tombstones': Input/output error
ls: cannot access 'mnt': Input/output error
total 1476
[…]
?????????? ? ?   ?        ?            ? mnt
[…]
?????????? ? ?   ?        ?            ? sdcard
[…]
```

**Comment by wolpi** [comment] 2016-06-25 12:05
Does the directory `/storage` point to a sdcard? If so it is very likely caused by #31.

**Comment by ka223** [comment] 2016-08-13 20:22
I tested this app with CM13 and android 4.1, on both devices, the server starts at root of the phone.
Entered start folder is ignored. :/

**Comment by wolpi** [comment] 2016-08-14 13:00
That is strange. Can you post server logs here?

**Comment by ka223** [comment] 2016-08-15 08:16
@wolpi 
Thanks, I took a look to the logs myself and your server is sending the rootDir, I can confirm that it is working at filezilla.

` ...
2016-08-15 10:00:07.814";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"CREATED";"";
"2016-08-15 10:00:07.820";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"OPENED";"";
"2016-08-15 10:00:07.830";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"SENT: 220 Service ready for new user.
";"";
"2016-08-15 10:00:07.837";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"RECEIVED: USER user";"";
"2016-08-15 10:00:07.840";"DEBUG";"org.primftpd.AndroidPrefsUserManager";"rootDir: /mnt/sdcard";"";
"2016-08-15 10:00:07.856";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"SENT: 331 User name okay, need password for user.
";"";
"2016-08-15 10:00:07.869";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"RECEIVED: PASS *****";"";
"2016-08-15 10:00:07.870";"DEBUG";"org.primftpd.AndroidPrefsUserManager";"rootDir: /mnt/sdcard";"";
"2016-08-15 10:00:07.875";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"SENT: 230 User logged in, proceed.
";"";
"2016-08-15 10:00:07.879";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"RECEIVED: TYPE I";"";
"2016-08-15 10:00:07.883";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"SENT: 200 Command TYPE okay.
";"";
"2016-08-15 10:00:07.888";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"RECEIVED: OPTS UTF8 ON";"";
"2016-08-15 10:00:07.895";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"SENT: 200 Command OPTS okay.
";"";
"2016-08-15 10:00:07.898";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"RECEIVED: CWD /";"";
"2016-08-15 10:00:07.899";"TRACE";"org.primftpd.filesystem.FtpFileSystemView";"changeWorkingDirectory(/)";"";
"2016-08-15 10:00:07.900";"TRACE";"org.primftpd.filesystem.FtpFile";"getAbsolutePath()";"";
"2016-08-15 10:00:07.901";"TRACE";"org.primftpd.filesystem.FtpFileSystemView";"using path for cwd operation: /";"";
"2016-08-15 10:00:07.902";"TRACE";"org.primftpd.filesystem.FtpFileSystemView";"current WD '/mnt/sdcard', new path '/'";"";
"2016-08-15 10:00:07.902";"TRACE";"org.primftpd.filesystem.FtpFileSystemView";"getWorkingDirectory()";"";
"2016-08-15 10:00:07.903";"TRACE";"org.primftpd.filesystem.FtpFile";"getAbsolutePath()";"";
"2016-08-15 10:00:07.906";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"SENT: 250 Directory changed to /
";"";
"2016-08-15 10:00:07.913";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"RECEIVED: PASV";"";
"2016-08-15 10:00:07.915";"DEBUG";"org.apache.ftpserver.impl.IODataConnectionFactory";"Initiating passive data connection";"";
"2016-08-15 10:00:07.916";"DEBUG";"org.apache.ftpserver.impl.IODataConnectionFactory";"Opening passive data connection on address "/192.168.****" and port 0";"";
"2016-08-15 10:00:07.916";"DEBUG";"org.apache.ftpserver.impl.IODataConnectionFactory";"Passive data connection created on address "/192.168.****" and port 0";"";
"2016-08-15 10:00:07.919";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"CREATED";"";
"2016-08-15 10:00:07.921";"INFO";"org.apache.ftpserver.listener.nio.FtpLoggingFilter";"SENT: 227 Entering Passive Mode (192,168,178,31,194,140)
... `

At my linux file manager, it is switching back to / somehow, but I think nothing you should worry about.

**Comment by wolpi** [comment] 2016-08-30 20:42
ok, i'm closing this now

**Closed by wolpi** 2016-08-30 20:42 UTC
