### ISSUE TITLE
Address repeated when reopening QR tab

### ISSUE THREAD

**Issue by trikaphundo** [wolpi/prim-ftpd#380] opened 2024-09-26 19:54 UTC
## The problem
On the QR-code tab, the connection address repeats, making up a stack, when reopening the application from the recents.

## Steps to reproduce the problem
1. Open primitive FTPd application and start the FTP server
2. Switch to QR-code tab. Notice the address above the QR image.
3. Leave the application by tapping the middle button of Android's [navigation bar](https://developer.android.com/design/ui/mobile/guides/foundations/system-bars#navigation-bar).
4. Bring back the application by means of the Overview button of Android's navigation bar.
5. Notice the address above the QR-code image has doubled. See the next image

![pFTPd-bug-qr-code](https://github.com/user-attachments/assets/e5b6c871-2339-4297-b82c-a9c987d30b51)

**Comment by lmagyar** [comment] 2024-09-28 08:30
I think this is a duplicate of #367.

**Comment by trikaphundo** [comment] 2024-09-28 10:54
> I think this is a duplicate of #367.

Yes, it seems so. Sorry, I should have searched the open issues before filing a new one.

**Comment by wolpi** [comment] 2024-09-29 10:25
Closing this one

**Closed by wolpi** 2024-09-29 10:25 UTC
