### ISSUE TITLE
/storage, /sdcard and other directories are not readable using SFTP after upgrade v4.4 => v4.5

### ISSUE THREAD

**Issue by 1-eric** [wolpi/prim-ftpd#68] opened 2016-06-27 01:44 UTC
After upgrading from v4.4 to v4.5 some directories are not readable anymore. All settings of the phone and this app are the same.
Downgrading back to v4.4 (after uninstalling v4.5) makes these directories readable again.

When on v4.5 I do `ls -l /` I get an "Input/output error" message for every directory that is not readable, and every unreadable directory looks like this: `?????????? ? ?    ?          ?             ? storage`.

**Comment by licaon-kter** [comment] 2016-06-27 03:56
SFTP or FTP?

**Comment by 1-eric** [comment] 2016-06-27 12:10
Sorry, I forgot to mention that this only happened using SFTP.
Even though I never use FTP, the directories are readable using FTP in v4.5.

**Comment by licaon-kter** [comment] 2016-06-27 12:15
Device? Android version? prim-ftpd source (F-Droid or Google Play store)?

**Comment by 1-eric** [comment] 2016-06-27 12:49
Device: Xiaomi Redmi-2
Android: Official ROM (MIUI) based on Android-4.4.4
Source: F-Droid

**Comment by wolpi** [comment] 2016-06-27 19:38
Sounds to me like it could be caused by the sym-link changes made for #57. Can you give us some paths that are not working anymore?

**Comment by 1-eric** [comment] 2016-06-28 01:16
The paths that are not working (all in the / directory): d, etc, mnt, sdcard, storage, tombstones and vendor.
All these paths are symbolic links, except: mnt and storage.

**Comment by wolpi** [comment] 2016-06-29 19:48
will have a look at it, will take some weeks

**Comment by wolpi** [comment] 2016-10-02 13:03
Made some changes to sym link handling. Hope that fixes it.

**Comment by 1-eric** [comment] 2016-10-06 17:41
Version 4.6 has the same issue as 4.5.
So I'm back with version 4.4.

When I tested the 4.6 version, it crashes right after starting the SSH-server because it can not find the ``authorized_keys`` file. The previous versions of prim-ftpd used the same file, but with a different name: ``authorized_key.pub``. Renaming the file and restarting the app solved the problem.

**Comment by wolpi** [comment] 2016-10-06 19:24
So it is not fixed :weary:

Can you post logs for the original issue please?

Will look Ingo Thema filename siehe.

**Comment by wolpi** [comment] 2016-10-10 21:42
> When I tested the 4.6 version, it crashes right after starting the SSH-server because it can 
> not find the authorized_keys file.

This has been fixed, thanks for reporting

**Comment by wolpi** [comment] 2016-10-23 20:01
I need logs to analyze that further

**Comment by MartiniMoe** [comment] 2016-10-27 14:29
I have the same error and attached my logs. Im trying to access /storage/emulated because /sdcard isnt even listed as a folder. Im using a Nexus 5 with Android 6.0.1 - CM 13 nightly 20161010. Hope this helps :)
[prim-ftpd-log.txt](https://github.com/wolpi/prim-ftpd/files/556127/prim-ftpd-log.txt)
Had to rename it to txt because github wouldnt accept csv ^^

**Comment by wolpi** [comment] 2016-11-02 21:02
It will take some more weeks until I find time to review :(

**Comment by licaon-kter** [comment] 2016-11-02 21:32
Have this also, Xperia 5.1.1
You can specify the folder in the FTP client, say Download and it will be opened ok.

**Comment by wolpi** [comment] 2016-11-16 21:16
As you can see by the commit comment I made changes for this. Is some of you able to test before it's released?

**Comment by MartinX3** [comment] 2017-01-28 11:47
Same with 4.7.

**Comment by wolpi** [comment] 2017-02-18 21:42
another try to close this 😉

**Closed by wolpi** 2017-02-18 21:42 UTC
