### ISSUE TITLE
Tasker plugin does not work (with Automate)

### ISSUE THREAD

**Issue by rpallai** [wolpi/prim-ftpd#82] opened 2016-11-01 10:38 UTC
Automate cannot control prim-ftpd meanwhile works well on other apps (with Tasker plugin) like Easy Voice Recorder, Overlays. I can select the desired action but nothing happens when triggering.

**Comment by wolpi** [comment] 2016-11-16 21:33
are there some developer docs for Automate?

**Comment by rpallai** [comment] 2016-12-22 16:32
It is fully compatible with Tasker.

http://llamalab.com/automate/

**Comment by wolpi** [comment] 2017-01-14 21:38
can you post logs of such a case?

**Comment by wolpi** [comment] 2017-01-25 21:05
I had a look at logs myself. It seems that automate is not sending any intent at all. So it seems like an issue of automate.

Do you have another app with tasker plugin that works with automate?

**Comment by Larx** [comment] 2017-03-18 16:31
I habe a maybe similar situation: The Tasker plugin only works when the screen is on?!

**Comment by wolpi** [comment] 2017-03-20 21:40
> I habe a maybe similar situation

Do you use it with tasker or with automate?

> The Tasker plugin only works when the screen is on?!

Could be. Will take some weeks until I find time to check.

**Comment by Larx** [comment] 2017-03-21 05:57
Tasker. I use the AutoRemote plugin to start/stop the server for remote access and alternative a profile to stop the server when leaving my WLAN. Both work only with screen on.

**Comment by wolpi** [comment] 2017-03-23 20:44
> Tasker

Create a new issue please, as in your case it is likely another root cause.

**Comment by rpallai** [comment] 2017-05-13 08:13
> Do you have another app with tasker plugin that works with automate?

Yes, Easy Voice Recorder for example.

**Comment by shubham81** [comment] 2021-08-22 18:50
It doesn't work with macro droid so I have to create a work-around just don't know why it doesn't work please help

**Comment by wolpi** [comment] 2021-08-24 20:43
Well, it does not work as automate does not provide propper developer documentation. I can check macro droid, maybe it can be made workiing this time. Not sure when I find time for this.

**Comment by wolpi** [comment] 2023-02-04 11:34
Tasker plugins work by sending Intents following a defined protocol. In recent Android versions apps have to define custom permissions to be allowed to send Intents to other apps. Such permissions have been added to this app and will be part of next version.

**Comment by wolpi** [comment] 2023-04-23 11:12
Please give feedback if this issue have been resolved with version 6.16

**Comment by lmagyar** [comment] 2024-06-22 22:11
Just info for those who still has this problem (though seems to be an Automate issue, in my case other Tasker plugins also do not work with Automate, I can configure them, but when I start them, nothing happens).

Instead of the Tasker plugin, select the "Start an app activity" block, and set:
- Package: org.primftpd
- Activity class: org.primftpd.ui.StartServerAndExitActivity ***or*** org.primftpd.ui.StartServerAndExitActivity
- Action: android.intent.action.MAIN

**Comment by wolpi** [comment] 2024-06-23 11:07
That is a good opportunity to close this.

**Closed by wolpi** 2024-06-23 11:07 UTC
