### ISSUE TITLE
Hidden files

### ISSUE THREAD

**Issue by am-trouzine** [wolpi/prim-ftpd#198] opened 2020-04-26 03:25 UTC
The application doesn't serve hidden files whose file names start with a dot.
I couldn't find an option to turn this feature on.

**Comment by wolpi** [comment] 2020-04-26 21:13
This is a duplicate of #53.
Let's see when I find time to look at this again

**Comment by wolpi** [comment] 2020-08-08 14:08
That is changed now

**Closed by wolpi** 2020-08-08 14:08 UTC
