### ISSUE TITLE
Zero file output in root mode

### ISSUE THREAD

**Issue by aario** [wolpi/prim-ftpd#163] opened 2018-10-14 22:18 UTC
In FTP mode with super user mode selected, received jpeg file is corrupt.

Phone HTC 10.
Operating system is LineageOS 7.1.2. Rooted.
Primitive FTPD version is 5.10 downloaded from f-droid.
Downloaded file with Filezilla 3.33.0 on Debian Sid.

**Comment by wolpi** [comment] 2018-12-16 22:56
Tell us more detail please.
Is file created with zero size?
Or has it some size but is corrupt?
How often does it happen? On each transfer?
Have you tried plain old filesystem? Does it happen there, too?
Can you share logs?

I noticed empty files (zero size) when ftp data connection cannot be established, might this be the case for you?

**Comment by aario** [comment] 2018-12-24 14:59
Hi,
Thanks for the reply.
Created file is zero byte.
It happens always on super user mode. Plain old works flawlessly but it cannot access memory card. Only internal storage.
I will try to provide logs next time.
Ftp connection was able to establish as I could use the plain old method using the same network setup.

**Comment by wolpi** [comment] 2018-12-25 21:37
> It happens always on super user mode. Plain old works flawlessly

That is interesting, makes me eager to see your logs :wink: 


> but it cannot access memory card.

That is due to android restrictions, see #145 for a recent discussion

**Comment by uvemas** [comment] 2019-02-21 18:55
Hi,

I have the same problem with sftp too. If I upload any file to the server the transfer goes fine (I can see the progress and see that all the bytes are being transferred) but once the transfer ends the result file has a size of 0 bytes. The same happens when I download a file from the server to my PC.

Here is a log (transferred file is host_setup.rst.txt, 2350 bytes):

[prova.pdf](https://github.com/wolpi/prim-ftpd/files/2890678/prova.pdf)

**Comment by wolpi** [comment] 2019-02-23 22:43
This still is mysterious.
To create FileOutputStream in root mode the app uses `dd`. The whole commandline looks like this:
`su -c "dd of=/storage/emulated/0/Documents/host_setup.rst.txt"`

Can you try to run this directly in a shell on your device?

The approach to use `dd` in root mode was introduced in #153. I hoped things would work better then but obviously they are not :sob:

**Comment by uvemas** [comment] 2019-02-24 07:51
Sorry for my ignorance but how can I access my PC filesystem via ADB? I've tried the following
> adb shell
> su -c "dd if=C:/Users/uvema/Documents/host_setup.rst.txt of=/storage/emulated/0/Documents/host_setupt.rst.txt"
and get the error:
dd: C:/Users/uvema/Documents/host_setup.rst.txt: No such file or directory

**Comment by wolpi** [comment] 2019-02-24 21:58
Accessing pc filesystem or uploading files is not possible in that situation. Otherwise this app would be useless :wink: 

When `dd` is started without `if` parameter it reads file content from `stdin`. The app starts it in this way and connects to `stdin` of the `dd` process to be able to write files as root (more detail about that is talked about in #153).

Doing this in an interactive shell means you can type characters into the file.

I would like to see if some error occurs that gives hints what's going wrong.


Do you use this app for longer time? Do you have used older versions and experienced this error there? Your log shows that changes from #145 are taking place in parallel. That was introduced in version 5.12. Thus it would be interesting to know if the error happened with version 5.11, too.

**Comment by uvemas** [comment] 2019-02-25 17:16
OK. Let me try it again...

```
$ adb shell
mido:/ $ echo "This is a silly text" | su -c "dd of=/storage/emulated/0/Documents/test_file.txt"            
0+1 records in                                                                                              
0+1 records out                                                                                             
21 bytes transferred in 0.001 secs (21000 bytes/sec)                                                        
mido:/ $ ca                                                                                                 
cal   case  cat                                                                                             
mido:/ $ cat /storage/emulated/0/Documents/test_file.txt                                                    
This is a silly text                                                                                        
mido:/ $                                                                                                    
```
I met this app for the first time when I moved to LineageOS 15 a few weeks ago. So 5.13 is th eonly version I've used.

**Comment by wolpi** [comment] 2019-02-26 22:52
Thanks for testing this. So the command works great and it is still not clear what the problem is. I try to add some more debug logging to figure it out. There might be a new version next week. Would be great if you could share updated logs then.

**Comment by uvemas** [comment] 2019-02-27 15:01
No problem, I'll share logs again.

**Comment by uvemas** [comment] 2019-05-05 10:16
Hi,
finally I've got some time for testing this problem on version 5.15. It is still there. You can see the attached log file.

The transferred file is named "Instalar dokuwiki.txt" and has a size of 856 bytes.

[prim-ftpd-log-2019-05-05-10-47-49.pdf](https://github.com/wolpi/prim-ftpd/files/3145400/prim-ftpd-log-2019-05-05-10-47-49.pdf)

**Comment by wolpi** [comment] 2019-05-12 21:43
Seems like there ist an issue with proper termination of dd process. I'm going to dive deeper into this ...

**Comment by wolpi** [comment] 2019-05-31 22:01
A new version is on it's way to app stores. Let's see if it fixes this.

**Comment by woj-tek** [comment] 2019-07-09 18:27
I just run in to exactly same problem - works in normal mode, in root mode writes 0 length
[prim-ftpd-log-2019-07-09-13-51-57.txt](https://github.com/wolpi/prim-ftpd/files/3374375/prim-ftpd-log-2019-07-09-13-51-57.txt)

 file.

OnePlus3, running Android 7.1.2 with Resurrection Remix. `dd` command works without issues:
```bash
OnePlus3:/storage/emulated/0/test # echo "some text" | dd of=test_file
0+1 records in
0+1 records out
10 bytes transferred in 0.001 secs (10000 bytes/sec)
OnePlus3:/storage/emulated/0/test # ls -lah
total 4.0K
drwxrwx--x  2 root sdcard_rw 4.0K 2019-07-09 14:25 .
drwxrwx--x 30 root sdcard_rw 4.0K 2019-07-09 14:25 ..
-rw-rw----  1 root sdcard_rw   10 2019-07-09 14:25 test_file
OnePlus3:/storage/emulated/0/test # cat test_file
some text
```

Attached is the log.

**Comment by wolpi** [comment] 2019-07-13 21:52
hmmm, the log contains no entry about closing the file. That means recent changes have no effect as affected code is not called at all.
Which client do you use?
Can you try a different client?

**Comment by woj-tek** [comment] 2019-07-14 01:52
I was using macOS ForkLift. I just tried with shell ftp:

Test files:
```
wojtek@atlantiscity.local ~/dev/tmps $ cat test_normal
this is a test
wojtek@atlantiscity.local ~/dev/tmps $ cat test_root
test root
wojtek@atlantiscity.local ~/dev/tmps $ ls -lah test_*
-rw-r--r-- 1 wojtek staff 15 Jul 13 21:29 test_normal
-rw-r--r-- 1 wojtek staff 10 Jul 13 21:41 test_root
```

Normal writing:
```
wojtek@atlantiscity.local ~/dev/tmps $ ftp -dv 192.168.43.1 9999
Connected to 192.168.43.1.
220 Service ready for new user.
Name (192.168.43.1:wojtek): a
---> USER a
331 User name okay, need password for a.
Password:
---> PASS XXXX
230 User logged in, proceed.
ftp> cd test
---> CWD test
250 Directory changed to /storage/emulated/0/test
ftp> put test_normal
---> PORT 192,168,43,70,217,77
200 Command PORT okay.
---> STOR test_normal
150 File status okay; about to open data connection.
226 Transfer complete.
16 bytes sent in 0.000104 seconds (150 kbytes/s)
ftp> ls -lah
---> PORT 192,168,43,70,217,82
200 Command PORT okay.
---> LIST -lah
150 File status okay; about to open data connection.
-rw-------   0 a a           15 Jul 13 21:45 test_normal
226 Closing data connection.
ftp> quit
---> QUIT
221 Goodbye.
```

ROOT:
```
wojtek@atlantiscity.local ~/dev/tmps $ ftp -dtv 192.168.43.1 9999
Connected to 192.168.43.1.
220 Service ready for new user.
Name (192.168.43.1:wojtek): a
---> USER a
331 User name okay, need password for a.
Password:
---> PASS XXXX
230 User logged in, proceed.
ftp> cd test
---> CWD test
250 Directory changed to /storage/emulated/0/test
ftp> ls
---> PORT 192,168,43,70,218,94
200 Command PORT okay.
---> LIST
150 File status okay; about to open data connection.
-rw-------   0 a a           15 Jul 13 17:45 test_normal
226 Closing data connection.
ftp> put test_root
---> PORT 192,168,43,70,218,104
200 Command PORT okay.
---> STOR test_root
150 File status okay; about to open data connection.
226 Transfer complete.
11 bytes sent in 9.2e-05 seconds (117 kbytes/s)
ftp> ls
---> PORT 192,168,43,70,218,105
200 Command PORT okay.
---> LIST
150 File status okay; about to open data connection.
-rw-------   0 a a           15 Jul 13 17:45 test_normal
-rw-------   0 a a            0 Jul 13 17:46 test_root
226 Closing data connection.
ftp> quit
---> QUIT
221 Goodbye.
```

Attaching log file (start application, enable log, start ftp-service in normal mode, transfer `test_normal` file, stop ftp-service, select root mode and start ftp-service again, attempt transfer `test_root`): [prim-ftpd-log-2019-07-13-21-44-04.log](https://github.com/wolpi/prim-ftpd/files/3389382/prim-ftpd-log-2019-07-13-21-44-04.log)

I hope this helps. I can run more test with different applications or some client that may have more verbose debug (ideas welcomed)

Btw. yes, primitive-ftpd has root permissions.

**Comment by wolpi** [comment] 2019-07-14 21:11
At least I was able to reproduce it now. But I get zero length files for filesystem, too :sob: 

Analyzing this further ...

**Comment by wolpi** [comment] 2020-01-15 21:47
Version 6.0 is on it's way to app stores

**Closed by wolpi** 2020-01-15 21:47 UTC
