### ISSUE TITLE
Cannot get external sd directory listing because of .android_secure

### ISSUE THREAD

**Issue by substanceof** [wolpi/prim-ftpd#84] opened 2016-12-25 00:13 UTC
When i try to get listing of `/storage/60ed9798-xxx[sdcard uuid]` filezilla fails with
```
Status:	Listing directory /storage/60ed9798-xxx
Error:	Reading directory .: received failure with description '/storage/60ed9798-xxx/.android_secure'
```
if I enter the path to a specific directory on external sd manually then all works ok
```
Status:	Retrieving directory listing of "/storage/60ed9798-xxx/Music"...
Status:	Listing directory /storage/60ed9798-xxx/Music
Status:	Directory listing of "/storage/60ed9798-xxx/Music" successful
```
This problem occurs only with sftp server
Android 6.0.1 / Cyanogenmod 13, primitive ftpd 4.7 (code: 21)

**Comment by wolpi** [comment] 2016-12-28 19:48
can you post server logs of the failure?

**Comment by substanceof** [comment] 2016-12-29 13:32
https://gist.github.com/substanceof/60bb05079f4bf54b387cae385abfdc96

**Comment by wolpi** [comment] 2016-12-29 20:53
Looks like the Java method `file.exists()` returns a wrong value. Can you post 2 more things:
* Output of `ls -l` for that file 
* Content of that file

**Comment by substanceof** [comment] 2016-12-29 21:34
```
root@m8:/storage/60ed9798-a4a7-49b8-b149-4571a2ec6c2d # ls -al
ls: ./.android_secure: Permission denied
total 92
drwxrwx--x   17 0        1015          4096 Dec 29 17:41 .
drwxr-xr-x    5 0        0              100 Dec 28 12:36 ..
drwxrwx--x    4 0        1015          4096 Dec  5 16:29 Android
....
```
So I can't even provide contents

**Comment by wolpi** [comment] 2016-12-30 19:45
Ist happens in Android that permissions are set in a way that apps cannot access files. I'm going to make some changes to avoid the error in such a case.

**Comment by wolpi** [comment] 2017-01-14 21:55
After looking at this another time: it could have same root cause as #68.

Should be fixed anyway.

**Closed by wolpi** 2017-01-14 21:55 UTC
